backend/package.json: pin @elastic/elasticsearch
Pin @elastic/elasticsearch to 7.15.x for now because it seems
there is an issue with 7.16.0:

    > openrxv-backend@0.0.1 build
    > nest build

    node_modules/@elastic/elasticsearch/api/types.d.ts:2454:13 - error TS2456: Type alias 'AggregationsAggregate' circularly references itself.

    2454 export type AggregationsAggregate = AggregationsSingleBucketAggregate | AggregationsAutoDateHistogramAggregate | AggregationsFiltersAggregate | AggregationsSignificantTermsAggregate<any> | AggregationsTermsAggregate<any> | AggregationsBucketAggregate | AggregationsCompositeBucketAggregate | AggregationsMultiBucketAggregate<AggregationsBucket> | AggregationsMatrixStatsAggregate | AggregationsKeyedValueAggregate | AggregationsMetricAggregate
                     ~~~~~~~~~~~~~~~~~~~~~
    node_modules/@elastic/elasticsearch/api/types.d.ts:3209:13 - error TS2456: Type alias 'AggregationsSingleBucketAggregate' circularly references itself.

    3209 export type AggregationsSingleBucketAggregate = AggregationsSingleBucketAggregateKeys
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~