backend: pin pizzip at 3.0.x for now
Newer Pizzip seems to want the Blob type, which is only available
in Node.js v18.

    node_modules/pizzip/js/index.d.ts:123:67 - error TS2304: Cannot find name 'Blob'.

    123     generate(options: PizZip.GenerateOptions & { type: 'blob' }): Blob;